# Generated by Django 2.0.2 on 2018-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('BR', 'Bathroom'), ('GR', 'Garbage'), ('MW', 'Medical Waste'), ('OS', 'Oil Spill'), ('OT', 'Other')], default='BR', max_length=2),
        ),
    ]
