# Generated by Django 2.0.2 on 2018-04-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
