# Generated by Django 2.0.2 on 2018-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
