# Generated by Django 2.0.2 on 2018-05-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180516_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
