# Generated by Django 2.0.2 on 2018-05-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20180516_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='static_string',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
