# Generated by Django 2.0.2 on 2018-05-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_park_static_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
